#Kotlin
kotlin.code.style=official
#Dokka
kotlin.daemon.jvmargs=-Xmx3072M
#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true


# MPP
kotlin.native.ignoreDisabledTargets=true

group=me.kpavlov.kmons
version=0.1.0-SNAPSHOT
